### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [ArcaneChat/android#32]
ref: https://monitor.f-droid.org/builds/log/chat.delta.lite/300006914#site-footer `2024-10-07 01:29:04,488 ERROR: Found usual suspect 'com.google.gms' at build.gradle`

so I remove  that line here https://github.com/ArcaneChat/android/blob/v1.46.20/build.gradle#L3 and here https://github.com/ArcaneChat/android/blob/v1.46.20/build.gradle#L129

but now it's not repro any more, here is the diff log: [chat300006924.log](https://github.com/user-attachments/files/17277781/chat300006924.log)

what did I miss?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/1424de9b3b55d70f3c8f136439d942623835687e

**Comment by licaon-kter** [comment]
> what about fixing the detector?

indeed the scanner is not a scalpel, but more like a hammer :laughing: 

> ah it is about the plugin, I can't remove that and I think the plugin itself is open source 🤷‍♂️

we don't care what you put in THAT flavor.

do read the diff log, notice how your FOSS APKs still have "google" strings references?

**Comment by adbenitez** [comment]
> do read the diff log, notice how your FOSS APKs still have "google" strings references?

what diff log? I read the [log you pointed out](https://monitor.f-droid.org/builds/log/chat.delta.lite/300006914#site-footer) and all it says is `ERROR: Found usual suspect 'com.google.gms' at build.gradle` so there is no closed source in the FOSS variant, it is only about the build.gradle containing [com.google.gms.google-services](https://github.com/google/play-services-plugins/tree/main/google-services-plugin) gradle plugin [WHICH IS OPEN SOURCE](https://github.com/google/play-services-plugins/blob/main/LICENSE) under Apache License 2.0 

so I don't think there is anything to be fixed here in this repo but in fdroid machinery???

**Comment by licaon-kter** [comment]
@adbenitez are we lost in translation?

you say that you don't see the `chat300006924.log` diff log that I attached in the OP? :eye:

**Comment by adbenitez** [comment]
> you say that you don't see the `chat300006924.log` diff log that I attached in the OP? 👁️

what has that file to do with the problem of the false positive? that file is about a failure due to some changes you made in the gradle.build

**Comment by adbenitez** [comment]
> https://github.com/ArcaneChat/android/blob/v1.46.20/build.gradle#L3 is this free software too? If not, can I remove it?

I already said [here](https://github.com/ArcaneChat/android/issues/32#issuecomment-2396844754) that it is perfectly fine Apache 2.0 free software



> https://github.com/ArcaneChat/android/blob/v1.46.20/build.gradle#L129 if I don't build this flavor, why can't I remove this line?

you can remove that line, what you can't remove is the plugin line you mentioned in your previous question, but there is not point in removing it and sed-ing in the build.gradle in this case

**Comment by adbenitez** [comment]
I opened an issue about the real problem of detecting a free software gradle plugin as closed source  and invalidating the building process here: https://gitlab.com/fdroid/fdroiddata/-/issues/3399

**Comment by adbenitez** [comment]
fixed by https://gitlab.com/fdroid/fdroid-suss/-/merge_requests/39

**Comment by licaon-kter** [comment]
confirmed ok: https://gitlab.com/fdroid/fdroiddata/-/commit/c47552498ec602acc5eacb7999b4804695eabca7

thanks

sorry for my confusion :smile_cat:
