### ISSUE TITLE
v1.49.0 failed Reproducible Build

### ISSUE THREAD

**Issue by IzzySoft** [ArcaneChat/android#37]
RB for ArcaneChat v1.49.0 failed today, with a minor diff:

```diff
  -rw-r--r--  0.0 unx   120576 b-    55756 defN 1981-01-01 01:01:02 6a938a4c lib/armeabi-v7a/libanimation-decoder-gif.so
- -rw-r--r--  0.0 unx 15064532 b-  8702468 defN 1981-01-01 01:01:02 d89cbd54 lib/armeabi-v7a/libnative-utils.so
+ -rw-r--r--  0.0 unx 15460872 b-  8873107 defN 1981-01-01 01:01:02 489a3192 lib/armeabi-v7a/libnative-utils.so
  -rw-r--r--  0.0 unx    13904 b-     6477 defN 1981-01-01 01:01:02 556ec7c2 lib/armeabi-v7a/libos-compat.so
```

Is there any dependency we didn't pin – or were there any changes on your end not reflected by our build recipe? I cannot yet tell, but F-Droid's RB would probably fail as well. What comes to mind is the NDK version (23.2.8568313 here), or cargo-ndk (but that should be handled by your `scripts/ndk-make.sh` I guess). Oh, and rustup – which according to the recipe is pinned to 1.25.1 (2 years old, current would be 1.27.1).

May I ask what was used by your build? And is there a place in your repo where I could find that myself (next time) without stealing your time?

**Comment by adbenitez** [comment]
ah yes! NDK was updated to 27, you can see how the apk is built in the .github/workflows folder

**Comment by IzzySoft** [comment]
> ah yes! NDK was updated to 27

So I read that right, thanks! Can you tell me the full version number? I guess it's `27.2.12479018`? As that seems the only `r27` listed on the [NDK download pages](https://developer.android.com/ndk/downloads) (usually there's a `.0` and `.1` as well if there's a `.2`), let me try with that…

(btw: something like [this](https://github.com/Oppzippy/OpenSCQ30/blob/master/.build-tool-versions) would be nice to have here as well, so all relevant versions could be looked up in one place and cross-checked easily)

Unfortunately, just going with r27c did not help, though we got closer (in size of the `.so`):

```
  -rw-r--r--  0.0 unx   120576 b-    55756 defN 1981-01-01 01:01:02 6a938a4c lib/armeabi-v7a/libanimation-decoder-gif.so
- -rw-r--r--  0.0 unx 15064532 b-  8702468 defN 1981-01-01 01:01:02 d89cbd54 lib/armeabi-v7a/libnative-utils.so
+ -rw-r--r--  0.0 unx 15064388 b-  8702346 defN 1981-01-01 01:01:02 ddce4481 lib/armeabi-v7a/libnative-utils.so
  -rw-r--r--  0.0 unx    13904 b-     6477 defN 1981-01-01 01:01:02 556ec7c2 lib/armeabi-v7a/libos-compat.so
```

On [their releases page](https://github.com/android/ndk/releases) I see there indeed was a r27b and a "a" (just r27, without a letter). So another run with `27.0.12077973` then (as you have no "b" (27.1.12297006) or "c" (27.2.12479018) in your spec)…

Yupp, that did the trick: RB again, thanks! Leaving the issue open for your response re: [`.build-tool-versions`](https://github.com/Oppzippy/OpenSCQ30/blob/master/.build-tool-versions) (central point for lookup). Would that be something you'd consider?
